### ISSUE TITLE
feature request: list my repositories sorted by star count

### ISSUE THREAD

**Issue by andrewrk** [melissanoelle/hubflow#1] opened 2015-05-09 20:18 UTC
I'm not sure if this fits into your project or not but that's something I've wanted for a while. Maybe it could be the way that the user chooses which project to triage?

**Comment by malakada** [comment] 2015-05-09 20:20
Duplicate of #2.

**Closed as completed by malakada** 2015-05-09 20:20 UTC

**Comment by malakada** [comment] 2015-05-09 20:21
![trollface](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB3e9fnboPhVaB0UY9imBPPScq3_DqHojn2Te8GXhqdyYfGYOoNbyQBMg)
